version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker build --tag slach/archstrap:$CIRCLE_BRANCH .
     #- run: docker push company/app:$CIRCLE_BRANCH

#echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
