version: 2.1

jobs:

  build:
    resource_class: small
    docker:
      - image: docker:20.10.11-git
    steps:
      - run:
          name: "Display kernel version"
          command: uname -a
      - checkout
      - run:
          name: "Checkout subrepositories"
          command: |
            git submodule update --recursive --init
            git submodule sync --recursive
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: "Build docker image"
          command: >
            docker build
            --tag slach/archstrap:$CIRCLE_SHA1
            --build-arg archlinux_mirror_url=https://mirrors.kernel.org/archlinux
            --build-arg login=slach
            .
      - run:
          name: "Push docker image"
          command: |
            docker login -u slach -p $DOCKERHUB_PASSWORD
            docker push slach/archstrap:$CIRCLE_SHA1

  bootloader:
    machine:
      image: ubuntu-2004:202111-02
      resource_class: medium
    steps:
      - run:
          name: "Generate bootloader image"
          command: |
            docker run -v `pwd`:/data --rm slach/groob
      - store_artifacts:
          path: groob.img

  filesystems:
    machine:
      image: ubuntu-2004:202111-02
      resource_class: medium
    steps:
      - run:
          name: "Extract tarball from docker image"
          command: |
            docker run -it -d --rm --name archstrap slach/archstrap:$CIRCLE_SHA1 sh
            docker export archstrap > archstrap.tar
            docker stop archstrap
      - run:
          name: "Create filesystems"
          command: |
            mkdir -p tarball
            tar -xf archstrap.tar -C tarball
            tar -cf root.tar --exclude=home -C tarball .
            tar -cf home.tar -C tarball/home .
            ls -lah `pwd`
            docker run -v `pwd`:/data --rm slach/tar2ext4:stable home.tar home.img 2G
            docker run -v `pwd`:/data --rm slach/tar2ext4:stable root.tar root.img 10G
            ls -lah `pwd`
      - store_artifacts:
          path: home.img

workflows:
  build-and-push:
    jobs:
      - build
      - bootloader
      - filesystems:
          requires:
            - build
            - bootloader
