version: 2.1

jobs:

  build:
    docker:
      - image: docker:20.10.11-git
    steps:
      - run:
          name: "Display kernel version"
          command: uname -a
      - checkout
      - run: 
          name: "Checkout subrepositories"
          command: >
            git submodule update --recursive --init
            git submodule sync --recursive
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: "Build docker image"
          command: >
            docker build
            --tag slach/archstrap
            --build-arg archlinux_mirror_url=https://mirrors.kernel.org/archlinux
            --build-arg login=slach
            .
      - run:
          name: "Push docker image"
          command: |
            docker login -u slach -p $DOCKERHUB_PASSWORD
            docker push slach/archstrap

workflows:
  build-and-push:
    jobs:
      - build
