version: 2.1

jobs:

  build:
    docker:
      - image: docker:20.10.11-git
    steps:
      - run:
          name: "Display kernel version"
          command: uname -a
      - checkout
      - run: 
          name: "Checkout subrepositories"
          command: |
            git submodule sync --recursive &&
            git submodule update --recursive --init
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: "Build docker image"
          command: >
            docker build
            --tag slach/archstrap
            --build-arg archlinux_mirror_url=https://mirrors.kernel.org/archlinux
            --build-arg login=slach
            .

  push:
    docker:
      - image: docker:20.10.11-git
        auth:
          username: $DOCKERHUB_LOGIN
          password: $DOCKERHUB_PASSWORD
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: "Push docker image"
          command: docker push slach/archstrap

workflows:
  build-and-push:
    jobs:
      - build
      - push:
          requires:
            - build
